{
 "title": ".NET Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Threads",
   "type": "timeseries",
   "description": "Общие метрики связанные с потоками",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(process_thread_count{instance=\"async-api:8080\"})",
     "legendFormat": "Async-api threads"
    },
    {
     "expr": "sum(process_thread_count{instance=\"sync-api:8080\"})",
     "legendFormat": "Sync-api threads"
    },
    {
     "expr": "sum(dotnet_thread_pool_thread_count_total{instance=\"async-api:8080\"})",
     "legendFormat": "Async-api thread pool count"
    },
    {
     "expr": "sum(dotnet_thread_pool_thread_count_total{instance=\"sync-api:8080\"})",
     "legendFormat": "Sync-api thread pool count"
    }
   ]
  },
  {
   "title": "HTTP request failures",
   "type": "stat",
   "description": "Общее количество ошибочных запросов",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "http_server_request_duration_seconds_count{http_response_status_code=~\"5..|4..|0\",http_request_method=\"GET\",http_route=\"/async-work\"}",
     "legendFormat": "Async"
    },
    {
     "expr": "http_server_request_duration_seconds_count{http_response_status_code=~\"5..|4..|0\",http_request_method=\"GET\",http_route=\"/sync-work\"}",
     "legendFormat": "Sync"
    }
   ]
  },
  {
   "title": "HTTP requests",
   "type": "stat",
   "description": "Общее количество выполненных запросов на сервер",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_request_duration_seconds_count{http_request_method=\"GET\",http_route=\"/async-work\"}[$__rate_interval]))",
     "legendFormat": "Async"
    },
    {
     "expr": "sum(increase(http_server_request_duration_seconds_count{http_request_method=\"GET\",http_route=\"/sync-work\"}[$__rate_interval]))",
     "legendFormat": "Sync"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "description": "Количество запросов в секунду, которые без проблем проходят на сервер",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(k6_http_reqs_total{scenario=\"async_test\"}[$__rate_interval]))",
     "legendFormat": "Async"
    },
    {
     "expr": "sum(irate(k6_http_reqs_total{scenario=\"sync_test\"}[$__rate_interval]))",
     "legendFormat": "Sync"
    }
   ]
  },
  {
   "title": "Requests by URL",
   "type": "table",
   "description": "min/max/p95/p99 depends on the available Quantile Stats",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "histogram_quantile(0, sum by(le, name, method) (rate(k6_http_req_duration_seconds[$__rate_interval])))",
     "legendFormat": "min"
    },
    {
     "expr": "histogram_quantile(1, sum by(le, name, method) (rate(k6_http_req_duration_seconds[$__rate_interval])))",
     "legendFormat": "max"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, name, method) (rate(k6_http_req_duration_seconds[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, name, method) (rate(k6_http_req_duration_seconds[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "process_memory_usage_bytes / 1048576",
     "legendFormat": "{{instance}} process Mb usage"
    }
   ]
  },
  {
   "title": "k6 total requests",
   "type": "timeseries",
   "description": "Сколько всего HTTP-запросов сгенерировал k6",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 20 },
   "targets": [
    {
     "expr": "k6_http_reqs_total{app=~\"async|sync\",status=\"200\"}",
     "legendFormat": "{{app}} successfully requests count"
    },
    {
     "expr": "k6_http_reqs_total{app=~\"async|sync\",status=~\"5..|4..|0\"}",
     "legendFormat": "{{app}} error requests count"
    }
   ]
  }
 ]
}